name: VSCE Package Extension
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Package
        uses: lannonbr/vsce-action@master
        with:
          args: "package"

      - name: Upload Artefact
        uses: actions/upload-artifact@v2
        with:
          name: vscode-krusty-syntax
          path: ./*.vsix
